### ISSUE TITLE
POST req gets it

### ISSUE THREAD

**Issue by JohnTheBastard** [codefellows/cf-hack-challenge-1#1]
Here is the hex value of the Secret String: 
5C 27 73 65 63 72 65 74 30 78 16 01 EF BF BD 57
EF BF BD 01 05 09 01 EF BF BD 67 EF BF BD 01 EF
BF BD 68 EF BF BD 01 40 EF BF BD 5B EF BF BD 01
40 5A EF BF BD 01 EF BF BD EF BF BD EF BF BD EF
BF BD EF BF BD EF BF BD EF BF BD EF BF BD 1E 01
01 30 78 16 01 EF BF BD 57 EF BF BD 01 EF BF BD
58 EF BF BD 01 68 5D EF BF BD 01 04 01 68 55 EF
BF BD 01 EF BF BD 5F 19 01 EF BF BD EF BF BD EF
BF BD EF BF BD EF BF BD 01 10 07 EF BF BD 1E EF
BF BD 01 48 5E EF BF BD 01 04 68 5E EF BF BD 01
04 01 EF BF BD 04 EF BF BD 01 43 2C 0A 

As text:
\'secret0x�W�	�g��h�@�[�@Z���������0x�W��X�h]�hU��_�������H^�h^���C,

I just sent a POST request to the URL with some dummy data and got this as the response

**Comment by toastynerd** [comment]
Gotta be the plain text, there are actual human readable characters, not hex digits.
